# Start from an NVIDIA CUDA base image
# FROM nvidia/cuda:11.0-base-ubuntu20.04
# FROM nvidia/cuda:11.8.0-runtime-ubuntu20.04
FROM nvidia/cuda:11.8.0-devel-ubuntu20.04
LABEL maintainer="RadekDanecek"

# Set a non-interactive shell to avoid prompts during the build process
ARG DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages for X11 and OpenGL
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    g++ \
    libboost-dev \ 
    libegl1 \
    mesa-utils  \
    cmake \
    curl \
    wget \
    zip \ 
    unzip \
    nano \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /workspace/repos

# # Set the DISPLAY environment variable for X11 forwarding
# ENV DISPLAY=:0

# Add a startup script to the image
COPY install_38_docker.sh /usr/local/bin/install_script.sh
COPY startup_script.sh /usr/local/bin/startup_script.sh
COPY environment.yaml /workspace/environment.yaml
COPY requirements.txt /workspace/requirements.txt
RUN chmod +x /usr/local/bin/install_script.sh

# Set the script to run on container start
RUN bash /usr/local/bin/install_script.sh

# Set the script to run on container start
CMD ["/usr/local/bin/startup_script.sh"] 

